### ISSUE TITLE
Receive artnet data in python ?

### ISSUE THREAD

**Issue by zobyeg62** [cpvalente/stupidArtnet#12]
Hello. 
First of all thank you for your work, your module works very well!

I’m developing a show control console for a show, and I need to receive artnet data.
I’m desperately looking for a python module that would read artnet data for further processing. Do you know of a module that could help me?
I would also like to know if you are planning to develop a similar module.

Thanks for your help, and have a good day.

**Comment by cpvalente** [comment]
Thank you, happy that the package is helping.
I could probably try and help, I have half written some server side code. Would only need to implement the ArtPoll side of the protocol.

- How are you planning on receiving the data in the server side? would you just get an array of the selected universe?
- How much data are you planning to capture?
- Are you in need of specifically a python solution?
- ... and most important, what is your timeline?

we can maybe work something out

**Comment by emanuel12324** [comment]
I'm also interested on being able to receive artnet with this library. Say when you initialize the listener, you just say `stupidArtnet(startAddress, number of channels)` and it just returns an object that you can poll for a current dmx value. Something like `net.getChannelValue(channelNumber)`.

**Comment by cpvalente** [comment]
It would make sense to me that you would make a listener for a universe, something like

`server = stupidArnetServer(universe, net=0, subnet=0)`

you would probably then be able to see the data as you mention with `server.getChannelValue(channelNumber) `or perhaps in more friendly way `server.channels[channelNumber]`
 
However this is all running on a separate thread, I wonder if we would need a callback function on certain channels? this would allow you to use Art-Net to trigger actions in a program

`server.setListener(channelNumber, callback)`

I guess it depends on the intended use, would you have an example usage for this?

**Comment by emanuel12324** [comment]
I like the idea of both methods frankly, as well as your version of the
function calls.

Personally, my use-case is controlling stepper motors with artnet using a
rpi, so just getting a direct value is much more convenient for me.

But I could just as easily see folks wanting to trigger some action when a
dmx value changes or just every time a new packet comes in.

**Comment by cpvalente** [comment]
Not entirely sure on the best architecture here. I find it difficult to design a process that works for generic situations since the usage of a Server is usually quite deeply connected with logic.


I have player around with a few different structures and ended up default to just having a server running in another thread.
Are you able to review 4fbe8c356bbd951db86a017f5d10eb11a1e8de24 and give me some thoughts?

**Comment by emanuel12324** [comment]
Well I sent it some artnet data and it seems to handle it quite well. If you ask me, this is perfectly done and the callback function architecture works just fine. I don't know if it'll get bogged down if I send a full universe's worth of active data, but I tested it with a good number of channels and it was alright.

**Comment by cpvalente** [comment]
I would believe that receiving artnet data is pretty trivial for any sort of computer. Even a raspberry pi, however I don't have one handy to test.

Which device did you use?
Are there any other utility functions that you would see useful?

I will be giving it another pass before making tests and merging to master

**Comment by emanuel12324** [comment]
I was using a RPI 4B.

I'm not entirely sure how this works, but what kind of procedure is there for receiving different nets and subnets, along with different universes?

**Comment by cpvalente** [comment]
So far I have defaulted nets to 0 and only implemented universes.
You would need a object instance for every universe

**Comment by emanuel12324** [comment]
Well I suppose other than implementing that, I don't really have any further suggestions. Great job with the library

**Comment by cpvalente** [comment]
Hey @emanuel12324 , I see you have made a PR for a subnet implementation.
I have been working on the architecture of the server and was wondering if you could give me your opinion on a720cef6be4d64cc6b0eb43cd533f916b4546fc0

It expands the idea of adding callbacks, in which you can reuse the same server and add a listener for every universe, net, subnet combination you would like to listen to

**Comment by emanuel12324** [comment]
I like it! It's definitely a much more powerful and efficient architecture.

**Comment by cpvalente** [comment]
closing issue
