### ISSUE TITLE
compatibility with Circuitpython?

### ISSUE THREAD

**Issue by stanelie** [cpvalente/stupidArtnet#33]
Hello.

For various reasons, I have to work with Circuitpython instead of Micropython (some ESPNow shenanigans). However, this library, as it is, does not work. Various import statements fail.

For example, `import _thread` fails as there is no thread library/module in circuitpython.

Is there a way around this?

Thanks!

**Comment by cpvalente** [comment]
Hi @stanelie, 
the library was made initially for a series of workshops on creative coding, ie: the objective was to explain how datagrams are built and the code tries to be as explicit as possible.

The first hit on a google search is this thread from circuitpython, accompanied by a suggestion alternative
https://github.com/adafruit/circuitpython/issues/1124

I personally do not have intention of modifying the code here to be compatible, I suggest that you could create a fork and make the changes there. The Art-net specific part should be sufficiently well explained here

I am sorry if this is not the answer you hoped for

**Comment by stanelie** [comment]
Thanks for the follow up, no worries.

Cheers!
