### ISSUE TITLE
Publish your repo on PyPi for easier installation

### ISSUE THREAD

**Issue by isabelleletarte** [cpvalente/stupidArtnet#4]
Hello! It would be great if you could publish your repo on PyPi. I'm using your library in a project with multiple docker containers and it would be really nice to be able to install it by putting it in the _requirements.txt_ file.

**Comment by LRTNZ** [comment]
I agree, this would make it much easier to work with, and keep up-to-date.

**Comment by bwees** [comment]
Will this be happening anytime soon?

**Comment by cpvalente** [comment]
It is unlikely that I will have time to do it.
Also, as mentioned in the readme, there are plenty of alternatives out there for Art-Net.

Perhaps someone can fork the project and do the necessary work to publish to pypi

**Comment by cpvalente** [comment]
Reopening this as there is work moving towards publishing to Pypi

**Comment by cpvalente** [comment]
Looks like everything is up and running with pip since ea6cbdbb8910c766c3cbafdfa69ebc0b7ad6ad89
