### ISSUE TITLE
def set_16bit(self, address, value) --> wrong put_in_range

### ISSUE THREAD

**Issue by himijendrix24** [cpvalente/stupidArtnet#6]
line 203 should be 

`value = self.put_in_range(value, 0, 65535, False)`

instead of 

`value = self.put_in_range(value, 0, 255, False)`

It would also be useful to be able to select the HIGH and LOW byte channels, 
since every 16 bit DMX/Artnet device handles this different. 

On one moving head I have it is like this:
CH1 = PAN_COURSE
CH2 = PAN_FINE

On another one its like this:
CH1 = PAN_COURSE
CH3 = PAN_FINE

**Comment by cpvalente** [comment]
Thank you for the spot and the suggestion, fixed with https://github.com/cpvalente/stupidArtnet/commit/2dc2856e9cfd35faaa292507b4dfaa08f38a0ca8 and added option to modify endianess in https://github.com/cpvalente/stupidArtnet/commit/07e109467db2cf72570a42449ddaba83c09bd2af
