### ISSUE TITLE
Library not broadcast compatible yet

### ISSUE THREAD

**Issue by einzigw** [cpvalente/stupidArtnet#8]
When sending to a target IP that is a broadcast address following error gets output:
`ERROR: Socket error with exception: [Errno 13] Permission denied`

This can be resolved with changing the Socket initialisation to:
`self.s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM, socket.IPPROTO_UDP)
self.s.setsockopt(socket.SOL_SOCKET, socket.SO_BROADCAST, 1)`

Now to send ArtNet data in broadcast use the broadcast address as target IP (e.g. 2.255.255.255).
To send in Unicast just use a specific address for the target IP.

**Comment by cpvalente** [comment]
Thank you. 
This is being reviewed in the current pull request. It would be great if you would like to take a look

**Comment by cpvalente** [comment]
fixed with #7
